### ISSUE TITLE
Problem enabling plugin first time running embedded RabbitMQ

### ISSUE THREAD

**Issue by MarioKusek** [AlejandroRivera/embedded-rabbitmq#34]
When I clone my project from git and run it for the first time on machine that didn't download and extract RabbitMQ, and in test I have setting plugins like this:

```
@BeforeClass
public static void startEmbeddedRabbit() {
    EmbeddedRabbitMqConfig config = new EmbeddedRabbitMqConfig.Builder()
        .rabbitMqServerInitializationTimeoutInMillis(RABBIT_STARTING_TIMEOUT)
        .build();

    RabbitMqPlugins rabbitMqPlugins = new RabbitMqPlugins(config);
    rabbitMqPlugins.enable("rabbitmq_management");
    rabbitMqPlugins.enable("rabbitmq_tracing");

    rabbitMq = new EmbeddedRabbitMq(config);
    rabbitMq.start();
}
```

I got exception like this:
```
java.lang.IllegalArgumentException: The given command could not be found using the path: /var/folders/7v/56nk9qy52gb3hw658_q1kz840000gn/T/rabbitmq_server-3.6.9/sbin/rabbitmq-plugins
	at io.arivera.oss.embedded.rabbitmq.bin.RabbitMqCommand.<init>(RabbitMqCommand.java:110)
	at io.arivera.oss.embedded.rabbitmq.bin.RabbitMqPlugins.execute(RabbitMqPlugins.java:48)
	at io.arivera.oss.embedded.rabbitmq.bin.RabbitMqPlugins.getProcessResult(RabbitMqPlugins.java:148)
	at io.arivera.oss.embedded.rabbitmq.bin.RabbitMqPlugins.enable(RabbitMqPlugins.java:124)
	at eu.h2020.symbiote.messaging.ITests.startEmbeddedRabbit(ITests.java:100)
...
```

The reason is that when I call method `enable` in `RabbitMqPlugins` there is no current extracted version of RabbitMQ. 

The workaround is to comment 3 lines about setting plugin and run tests (which will download and extract RabbitMQ). After that I uncomment lines about setting plugins and then it works fine.

**Comment by AlejandroRivera** [comment]
@MarioKusek, `RabbitMqPlugins` assumes there's already an existing folder where the binaries are extracted to. The extraction only takes place when the `rabbitMq.start()` command is executed. Try switching the order like so:

```
EmbeddedRabbitMqConfig config = new EmbeddedRabbitMqConfig.Builder()
        .rabbitMqServerInitializationTimeoutInMillis(RABBIT_STARTING_TIMEOUT)
        .build();

    rabbitMq = new EmbeddedRabbitMq(config);
    rabbitMq.start();

    RabbitMqPlugins rabbitMqPlugins = new RabbitMqPlugins(config);
    rabbitMqPlugins.enable("rabbitmq_management");
    rabbitMqPlugins.enable("rabbitmq_tracing");
```

In regular RabbitMQ installations, you CAN use the `rabbitmq-plugins` command even when the broker isn't running because this command simply modifies the configuration file (although you'd need the `--offline` flag). This makes sense for regular installations because both files (command + config) already exist in the filesystem; however, for the "embedded" version we can't guarantee their existence. The only time we know for sure we MUST extract the compressed artifact into the filesystem is when the `start()` command is executed. Any extraction earlier than that implies effort spent preparing the system for something that might never be needed.

**Comment by MarioKusek** [comment]
OK. If I change the order as you proposed, will enabling plugins have effect on currently running RabbitMQ or do I need to restart it in order to have effect?

**Comment by AlejandroRivera** [comment]
It's automatic. 

See https://github.com/AlejandroRivera/embedded-rabbitmq/blob/master/src/test/java/com/sample/project/EmbeddedRabbitMqTest.java#L67-L98 for an example where this is done exactly like that.

**Comment by MarioKusek** [comment]
Thanks I will do it that way. You can close this issue.

**Comment by AlejandroRivera** [comment]
👍
