### ISSUE TITLE
RabbitMQ 3.8 ?

### ISSUE THREAD

**Issue by LeoMolina** [AlejandroRivera/embedded-rabbitmq#51]
Hello,

Is there any progress to support rabbitmq 3.8 ?

Regards,
Leo

**Comment by AlejandroRivera** [comment]
Hi Leo, 

I just tried to add 3.8.0 to the list of predefined versions; unfortunately, the RabbitMQ team hasn't uploaded any of the binaries Github (see their [releases](https://github.com/rabbitmq/rabbitmq-server/releases/)) or the complete set to Bintray (for example, the Mac OS binary is missing here: https://dl.bintray.com/rabbitmq/all/rabbitmq-server/3.8.0/). 

Since I'm not tracking their binary releases and/or making sure they all work, I can't guarantee that when they fix it, I will immediately release the new version of this library with support for 3.8.0.  I also can't release the version of this library offering support for 3.8.0 and just wait for them to upload the binaries for people's code to start working (because many will be using the `LATEST` tag and this will break their builds due to the missing binaries) 

If you want to make it your task to bring this issue to the RabbitMQ team's attention, and ping me when it's fixed, I can help out pushing the code and releasing a new version. If you want to submit a PR yourself, feel free to do so as well :)

I'd recommend that you use the custom download approach mentioned in the Readme in the meantime: https://github.com/AlejandroRivera/embedded-rabbitmq/blob/master/README.md#define-a-rabbitmq-version-to-use

LMK if you have any further questions and good luck!

**Comment by AlejandroRivera** [comment]
Ugh... just found out that they've stopped producing binaries for Mac since Sep. 2019:  https://www.rabbitmq.com/install-standalone-mac.html
This means the strategy for downloading binaries will need to be updated :/

However, if you use the custom download approach pointing to the generic linux url, things should still work as expected.

**Comment by AlejandroRivera** [comment]
Created new issue #52 to track progress to address this change in behavior.

**Comment by AlejandroRivera** [comment]
Support for RabbitMQ 3.8 has been added with release of v1.3.1. See [Releases](https://github.com/AlejandroRivera/embedded-rabbitmq/releases/tag/v1.3.1) for more info
