### ISSUE TITLE
Embedded Rabbit MQ is not downloading and starting after deleting .embeddedRabbitMQ Directory

### ISSUE THREAD

**Issue by VIGNESHBRB** [AlejandroRivera/embedded-rabbitmq#64]
Hi, 

I am using Embedded RabbitMQ for running Integration Tests. 
Earlier today, everything worked pretty well but after deleting .embeddedRabbitMQ directory and clearing the extracted files in Temp directory, I am not able to run anything smoothly. 

I am getting below exception, even newly it is not getting downloaded. 

**Code**
```
  var configBuilder = new EmbeddedRabbitMqConfig.Builder();
        configBuilder.downloadFrom(OfficialArtifactRepository.GITHUB);
        configBuilder.port(5673);
        configBuilder.useCachedDownload(false);
        var config = configBuilder.build();
        var command = new RabbitMqCommand(config, "rabbitmq-server", "start");
        command.call();
```
Need your help. 

**Exception Caused By**

```
java.lang.IllegalArgumentException: The given command could not be found using the path: C:\Users\<username>\AppData\Local\Temp\rabbitmq_server-3.8.0\sbin\rabbitmq-server.bat
```

**Comment by VIGNESHBRB** [comment]
@AlejandroRivera  Need your suggestion in resolving this issue.

**Comment by AlejandroRivera** [comment]
Hi @VIGNESHBRB...
It's going to be hard for me to help out here since i don't have a Windows machine i can test things, but do you see the logs where the file is being downloaded and extracted?  From the error message, it seems like the file isn't found and i imagine the issue is the extraction process failing for some reason.

The logs that show the extraction It should look like this: https://travis-ci.org/github/AlejandroRivera/embedded-rabbitmq/builds/463047276#L2522

If you don't see those logs, make sure to enabled `DEBUG`-level logs on your config (SLF4J or whatever logging library you're using). 

I'd also recommend you set a breakpoint in your test right before the test finishes and the tear-down takes place and then navigating on your filesystem to see the actual extracted files and ensuring things are there.

Good luck!

**Comment by VIGNESHBRB** [comment]
@AlejandroRivera Hi. Download and extraction is working fine after performing each operation separately. 

Like:

For Downloading:
```
  var downloaderFactory = new DownloaderFactory(config);
        var downloader = downloaderFactory.getNewInstance();
        downloader.run();
```

For Extracting:
```
   var extractorFactory = new ExtractorFactory(config);
        var extractor = extractorFactory.getNewInstance();
        extractor.run();
```

For Running: 
```
 var command = new RabbitMqCommand(config, "rabbitmqctl", "start_app");
        rabbitMqProcess = command.call().getFuture();
```

When I tried to use as given in README:

```
EmbeddedRabbitMq rabbitMq = new EmbeddedRabbitMq(config);
        rabbitMq.start();
```

I am getting: 
```
io.arivera.oss.embedded.rabbitmq.helpers.StartupException: Could not confirm RabbitMQ Server initialization completed successfully within 3000ms 
```

**Comment by AlejandroRivera** [comment]
Hi again,

Without having access to the logs from the process that's trying to start the RabbitMQ server it will be hard to know what's the issue. However, it's clear that the issue here is being able to run RabbitMQ on your host and it's not related to this library.

I'd suggest:
a) Determining if there's not already some process that was left hanging that's using the port number you're trying to use -- this is a common issue when RabbitMQ isn't properly terminated (like if your JVM instance crashes or you don't make it stop programmatically.
b) look for RabbitMQ log file. See http://www.rabbitmq.com/logging.html
c) Look for an Erlang's crash dump (`erl_crash.dump `). See https://www.rabbitmq.com/troubleshooting.html#crash-dumps
d) Manually download and run the RabbitMQ server (ie. without using this library) on your system. Once you're able to run it like that, you should also be able to run it using this library.

Good luck again!
